//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDKDecryption.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDKDecryption.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] privatekey {
            get {
                object obj = ResourceManager.GetObject("privatekey", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;RSAKeyValue&gt;&lt;Modulus&gt;yapfUQyiOpd0ozaGlBPpEkpN3KD7XLS6LyV48wXoRYnB2yYC6ok9uR05exyyROmY3BDsZXAy4axiLicI0QBpCa/vsnOl3NVUMbiQyqtU+pq/abVKth53oH31y2S2Iv5odf9X/ikeXXjVZDJ44uWqarPz5lmGr9PRxJFT2QqZqas=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;7lq4EvSPMUV0af7HuLnJ6ipeHwUwTlI7l06zcR34mvc0NFwoH0TpjKXRcfF43Irj9i7R9bAe4bPtgRuF5aIuYQ==&lt;/P&gt;&lt;Q&gt;2JhT7KlleDXDsMqm/4rdK1vgRPUtWXxSMz/3ZNL8P8Ep4wx9zMRMeFMyufITWjCRK/x74sTEltPM7DrgQ85biw==&lt;/Q&gt;&lt;DP&gt;NodYjzWVwK7kCA+6fz85uzGAINaeC3zylxXxJVK2+jTNo6DlqOmqCHwy4z9b6BB6QGrLq8pj9jykfCHgyv0EYQ==&lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string PrivateKey1 {
            get {
                return ResourceManager.GetString("PrivateKey1", resourceCulture);
            }
        }
    }
}
